name: Deploy Infrastructure
on: [push]
env:
  TERRAFORM_VERSION: 1.3.9
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: terraform format check
        run: terraform fmt -check